/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iznajmljivanjeapp;

import framework.App;
import framework.DbEngine;
import framework.config.AppConfig;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Djurkovic
 */
public class ConfigEdit extends javax.swing.JDialog {

        class MyListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            c();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            c();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            c();
        }

        private void c() {
            btnSave.setEnabled(!(
               txtDbDomain.getText().trim().isEmpty()
            || txtDbName.getText().trim().isEmpty()
            || txtDbPort.getText().trim().isEmpty()
            || txtDbUsername.getText().trim().isEmpty()
            || txtListeningPort.getText().trim().isEmpty())
            );
        }
        
    }
    
    
    
    
    
    private App app;

    /**
     * Creates new form ConfigEdit
     */
    public ConfigEdit(java.awt.Frame parent, boolean modal, App app) {
        super(parent, modal);
        initComponents();
        this.app = app;
        setLocationRelativeTo(null);
        cbDBEngine.setModel(new DefaultComboBoxModel<>(DbEngine.values()));

        var dl = new MyListener();
        var cfg = app.getAppConfig();

        txtDbPort.setText(cfg.getDbPortNumber() + "");
        txtDbPort.getDocument().addDocumentListener(dl);
        txtDbDomain.setText(cfg.getDbDomain());
        txtDbDomain.getDocument().addDocumentListener(dl);
        txtDbUsername.setText(cfg.getDbUsername());
        txtDbUsername.getDocument().addDocumentListener(dl);
        txtDbPassword.setEchoChar('*');
        txtDbPassword.setText(cfg.getDbPassword());
        cbDBEngine.setSelectedItem(cfg.getDbEngine());
        txtListeningPort.setText(cfg.getListeningPort() + "");
        txtListeningPort.getDocument().addDocumentListener(dl);
        txtDbName.setText(cfg.getImeBaze());
        txtDbName.getDocument().addDocumentListener(dl);
        
        ((AbstractDocument) txtDbPort.getDocument()).setDocumentFilter(new WholeNumberFilter());
        ((AbstractDocument) txtListeningPort.getDocument()).setDocumentFilter(new WholeNumberFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDbPort = new javax.swing.JTextField();
        txtDbDomain = new javax.swing.JTextField();
        txtDbUsername = new javax.swing.JTextField();
        txtListeningPort = new javax.swing.JTextField();
        cbDBEngine = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtDbPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtDbName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konfiguracija");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Konfiguracija servera");

        jLabel2.setText("Broj porta baze podataka:");

        jLabel3.setText("Domen baze podataka:");

        jLabel4.setText("Korisničko ime za bazu podataka:");

        jLabel5.setText("Šifra za bazu podataka:");

        jLabel6.setText("DBMS u upotrebi:");

        jLabel7.setText("Broj porta od servera:");

        jLabel8.setBackground(new java.awt.Color(255, 102, 102));
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Promene će postati efektivne pri prvom sledećem pokretanju.");

        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Resetuj na default konfiguraciju");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel9.setText("Ime baze podataka:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDbDomain)
                            .addComponent(txtDbPort)
                            .addComponent(txtDbUsername)
                            .addComponent(cbDBEngine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtListeningPort)
                            .addComponent(txtDbPassword)
                            .addComponent(txtDbName))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDbPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDbDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbDBEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtListeningPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnReset))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        app.setAppConfig(new AppConfig.Builder()
                .addDbHost("localhost")
                .addDbEngine(DbEngine.MYSQL)
                .addDbPortNumber(3306)
                .addImeBaze("projektovanjesoftvera_seminarski")
                .addImeTestBaze("projektovanjesoftvera_seminarski_test")
                .addListeningPort(9999)
                .addDbUsername("root")
                .addDbPassword("")
                .build()
        );
        JOptionPane.showMessageDialog(this, "Uspešno resetovana konfiguracija.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        var cfg = app.getAppConfig();
        cfg.setImeBaze(txtDbName.getText().trim());
        cfg.setDbPortNumber(Integer.parseInt(txtDbPort.getText().trim()));
        cfg.setDbDomain(txtDbDomain.getText().trim());
        cfg.setDbUsername(txtDbUsername.getText().trim());
        cfg.setDbPassword(new String(txtDbPassword.getPassword()).trim());
        cfg.setDbEngine((DbEngine) cbDBEngine.getSelectedItem());
        cfg.setListeningPort(Integer.parseInt(txtListeningPort.getText().trim()));
        JOptionPane.showMessageDialog(this, "Uspešno sačuvana konfiguracija.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<DbEngine> cbDBEngine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDbDomain;
    private javax.swing.JTextField txtDbName;
    private javax.swing.JPasswordField txtDbPassword;
    private javax.swing.JTextField txtDbPort;
    private javax.swing.JTextField txtDbUsername;
    private javax.swing.JTextField txtListeningPort;
    // End of variables declaration//GEN-END:variables
}
